on:
  push:
    branches: [main]
  workflow_dispatch:

name: Package

jobs:
  build:
    strategy:
      matrix:
        platform: [linux, windows]
        include:
          - platform: windows
            os: windows
            binext: .exe
          - platform: linux
            os: ubuntu
            binext: ""
    name: Build [${{ matrix.platform }}]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Run cargo build
        id: build
        run: cargo package
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.build.outputs.crate_name }}-${{ steps.build.outputs.crate_version }}-${{ matrix.platform }}.crate
          path: target/package/${{ steps.build.outputs.crate_name }}-${{ steps.build.outputs.crate_version }}.crate
